// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtrH4BjlQDZx85j6SvMBwnwtzZm_TD6Zw',
    appId: '1:250926958531:web:6798b1e192862e1a68df76',
    messagingSenderId: '250926958531',
    projectId: 'ev-charging-p2p',
    authDomain: 'ev-charging-p2p.firebaseapp.com',
    storageBucket: 'ev-charging-p2p.firebasestorage.app',
    measurementId: 'G-BNL6C0DJWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMSQ3eV83SPpPkux-nGcVxhfGdM6VgEo',
    appId: '1:250926958531:android:c7929a7a7cf00bf668df76',
    messagingSenderId: '250926958531',
    projectId: 'ev-charging-p2p',
    storageBucket: 'ev-charging-p2p.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQLkPGBylkmZyGwnuoxf0m2lvaxvv883k',
    appId: '1:250926958531:ios:803fb6d233d5954b68df76',
    messagingSenderId: '250926958531',
    projectId: 'ev-charging-p2p',
    storageBucket: 'ev-charging-p2p.firebasestorage.app',
    iosBundleId: 'com.example.evChargingP2p',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQLkPGBylkmZyGwnuoxf0m2lvaxvv883k',
    appId: '1:250926958531:ios:803fb6d233d5954b68df76',
    messagingSenderId: '250926958531',
    projectId: 'ev-charging-p2p',
    storageBucket: 'ev-charging-p2p.firebasestorage.app',
    iosBundleId: 'com.example.evChargingP2p',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtrH4BjlQDZx85j6SvMBwnwtzZm_TD6Zw',
    appId: '1:250926958531:web:af23b3cd2650f08968df76',
    messagingSenderId: '250926958531',
    projectId: 'ev-charging-p2p',
    authDomain: 'ev-charging-p2p.firebaseapp.com',
    storageBucket: 'ev-charging-p2p.firebasestorage.app',
    measurementId: 'G-QS6D69ZHFG',
  );
}
